---
  name: watcher

  on:
    workflow_dispatch:
    # pull_request:
    #   branches: [ main ]
    # push:
    #   branches: [ main ]
    # schedule:
    #   - cron:  '30 5,17 * * *'
    repository_dispatch:
      types:
        - workflow_run_watcher

  env:
    GHWATCHER_APP_ID: ${{ secrets.GHWATCHER_APP_ID }}
    GHWATCHER_APP_PEM: ${{ secrets.GHWATCHER_APP_PEM }}
    GHWATCHER_APP_INSTALLATION_ID: ${{ secrets.GHWATCHER_APP_INSTALLATION_ID }}
    GHWATCHER_CHECK_ORG: ${{ github.event.client_payload.organization || 'mydevsandbox-com' }}
    GHWATCHER_CHECK_REPO: ${{ github.event.client_payload.check_repo || null }}
    GHWATCHER_ENFORCE_PRIVATE: ${{ github.event.client_payload.enforce_private || null }}
    GHWATCHER_REPO_SKIP_LIST: ${{ github.event.client_payload.skip_list || 'watcher' }}
    GHWATCHER_ALLOWED_ORG_LIST: ${{ github.event.client_payload.allowed_org_list || 'mydevsandbox-com' }}
    GHWATCHER_ENABLE_DEPENDABOT: ${{ github.event.client_payload.allowed_org_list || null }}

  jobs:
    watcher_exec:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: 14.x
        - name: npm setup
          run: npm install
        - name: exec
          run: npx node github-action.js
